<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 17 Blocks | SOCR 580A7 Bookdown Portfolio</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 17 Blocks | SOCR 580A7 Bookdown Portfolio" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 17 Blocks | SOCR 580A7 Bookdown Portfolio" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Mary Dixon" />


<meta name="date" content="2022-03-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="class-work.html"/>
<link rel="next" href="sharing-your-book.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.0/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.0/leaflet-providers-plugin.js"></script>
<link href="libs/HomeButton-0.0.1/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton-0.0.1/home-button.js"></script>
<script src="libs/HomeButton-0.0.1/easy-button-src.min.js"></script>
<script src="libs/clipboard-0.0.1/setClipboardText.js"></script>
<link href="libs/mapviewCSS-0.0.1/mapview-popup.css" rel="stylesheet" />
<link href="libs/mapviewCSS-0.0.1/mapview.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#usage"><i class="fa fa-check"></i><b>1.1</b> Usage</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#render-book"><i class="fa fa-check"></i><b>1.2</b> Render book</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#preview-book"><i class="fa fa-check"></i><b>1.3</b> Preview book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hello-bookdown.html"><a href="hello-bookdown.html"><i class="fa fa-check"></i><b>2</b> Hello bookdown</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hello-bookdown.html"><a href="hello-bookdown.html#a-section"><i class="fa fa-check"></i><b>2.1</b> A section</a>
<ul>
<li class="chapter" data-level="" data-path="hello-bookdown.html"><a href="hello-bookdown.html#an-unnumbered-section"><i class="fa fa-check"></i>An unnumbered section</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>3</b> Methods</a>
<ul>
<li class="chapter" data-level="3.1" data-path="methods.html"><a href="methods.html#sitedescription"><i class="fa fa-check"></i><b>3.1</b> SiteDescription</a></li>
<li class="chapter" data-level="3.2" data-path="methods.html"><a href="methods.html#data-acquisition-and-plotting-tests"><i class="fa fa-check"></i><b>3.2</b> Data Acquisition and Plotting tests</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="methods.html"><a href="methods.html#data-download"><i class="fa fa-check"></i><b>3.2.1</b> Data Download</a></li>
<li class="chapter" data-level="3.2.2" data-path="methods.html"><a href="methods.html#static-data-plotter"><i class="fa fa-check"></i><b>3.2.2</b> Static Data Plotter</a></li>
<li class="chapter" data-level="3.2.3" data-path="methods.html"><a href="methods.html#interactive-data-plotter"><i class="fa fa-check"></i><b>3.2.3</b> Interactive Data Plotter</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="assignment..html"><a href="assignment..html"><i class="fa fa-check"></i><b>4</b> Assignment.</a>
<ul>
<li class="chapter" data-level="4.1" data-path="assignment..html"><a href="assignment..html#fork-the-example-repository-into-your-personal-github"><i class="fa fa-check"></i><b>4.1</b> 1) Fork the example repository into your personal GitHub</a></li>
<li class="chapter" data-level="4.2" data-path="assignment..html"><a href="assignment..html#create-an-rstudio-project-from-your-personal-clone-of-the-repo."><i class="fa fa-check"></i><b>4.2</b> 2) Create an RStudio project from your Personal clone of the Repo.</a></li>
<li class="chapter" data-level="4.3" data-path="assignment..html"><a href="assignment..html#create-a-table-of-contents-that-is-floating-but-displays-three-levels-of-headers-instead-of-two-by-editing-the-content-at-the-beginning-of-the-document"><i class="fa fa-check"></i><b>4.3</b> 3) Create a table of contents that is floating, but displays three levels of headers instead of two (by editing the content at the beginning of the document)</a></li>
<li class="chapter" data-level="4.4" data-path="assignment..html"><a href="assignment..html#make-a-version-of-the-dygraph-with-points-and-lines-by-using-rstudios-dygraph-guide"><i class="fa fa-check"></i><b>4.4</b> 4) Make a version of the <code>dygraph</code> with points and lines by using rstudio’s dygraph <span>guide</span></a></li>
<li class="chapter" data-level="4.5" data-path="assignment..html"><a href="assignment..html#writing-a-paragraph-on-the-poudre-river-with-at-least-three-hyperlinks-two-bolded-sections-and-one-italicized-phrase.-the-content-of-this-paragraph-is-not-vital-but-try-to-at-least-make-it-true-and-interesting-and-of-course-dont-plagiarize."><i class="fa fa-check"></i><b>4.5</b> 5) Writing a paragraph on the Poudre river with at least three hyperlinks, <strong>two bolded sections</strong>, and one <em>italicized phrase</em>. The content of this paragraph is not vital, but try to at least make it true and interesting, and, of course, don’t plagiarize.</a></li>
<li class="chapter" data-level="4.6" data-path="assignment..html"><a href="assignment..html#knit-that-document-and-then-git-commit-and-push-to-your-personal-github."><i class="fa fa-check"></i><b>4.6</b> 6) Knit that document, and then git commit and push to your personal GitHub.</a></li>
<li class="chapter" data-level="4.7" data-path="assignment..html"><a href="assignment..html#use-the-github---settings---pages-tab-to-create-a-website-of-your-report."><i class="fa fa-check"></i><b>4.7</b> 7) Use the GitHub -&gt; Settings -&gt; Pages tab to create a website of your report.</a></li>
<li class="chapter" data-level="4.8" data-path="assignment..html"><a href="assignment..html#bonus-make-the-timestamp-in-the-header-dynamic.-as-in-it-only-adds-todays-date-not-just-a-static-date-you-enter."><i class="fa fa-check"></i><b>4.8</b> 8) Bonus, make the timestamp in the header dynamic. As in it only adds today’s date, not just a static date you enter.</a></li>
<li class="chapter" data-level="4.9" data-path="assignment..html"><a href="assignment..html#bonus-create-an-index_talk.rmd-version-of-your-document-using-the-revealjs-package.-add-link-to-your-original-report-style-document."><i class="fa fa-check"></i><b>4.9</b> 9) Bonus, create an “index_talk.Rmd” version of your document using the <code>revealjs</code> package. Add link to your original report-style document.</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cross.html"><a href="cross.html"><i class="fa fa-check"></i><b>5</b> Cross-references</a>
<ul>
<li class="chapter" data-level="5.1" data-path="cross.html"><a href="cross.html#chapters-and-sub-chapters"><i class="fa fa-check"></i><b>5.1</b> Chapters and sub-chapters</a></li>
<li class="chapter" data-level="5.2" data-path="cross.html"><a href="cross.html#captioned-figures-and-tables"><i class="fa fa-check"></i><b>5.2</b> Captioned figures and tables</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="initial-setup.html"><a href="initial-setup.html"><i class="fa fa-check"></i><b>6</b> Initial Setup</a>
<ul>
<li class="chapter" data-level="6.1" data-path="initial-setup.html"><a href="initial-setup.html#loading-packages"><i class="fa fa-check"></i><b>6.1</b> Loading Packages</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="now-that-we-have-learned-how-to-munge-manipulate-data-and-plot-it-we-will-work-on-using-these-skills-in-new-ways.html"><a href="now-that-we-have-learned-how-to-munge-manipulate-data-and-plot-it-we-will-work-on-using-these-skills-in-new-ways.html"><i class="fa fa-check"></i><b>7</b> Now that we have learned how to munge (manipulate) data and plot it, we will work on using these skills in new ways</a>
<ul>
<li class="chapter" data-level="7.1" data-path="now-that-we-have-learned-how-to-munge-manipulate-data-and-plot-it-we-will-work-on-using-these-skills-in-new-ways.html"><a href="now-that-we-have-learned-how-to-munge-manipulate-data-and-plot-it-we-will-work-on-using-these-skills-in-new-ways.html#reading-files"><i class="fa fa-check"></i><b>7.1</b> Reading Files</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="assignment-2.html"><a href="assignment-2.html"><i class="fa fa-check"></i><b>8</b> Assignment 2</a>
<ul>
<li class="chapter" data-level="8.1" data-path="assignment-2.html"><a href="assignment-2.html#question-1"><i class="fa fa-check"></i><b>8.1</b> Question 1</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="assignment-2.html"><a href="assignment-2.html#what-is-the-correlation-between-ndvi-and-ndmi---here-i-want-you-to-convert-the-full_long-dataset-in-to-a-wide-dataset-using-the-function-spread-and-then-make-a-plot-that-shows-the-correlations-a-function-of-if-the-site-was-burned-or-not-x-axis-should-be-ndmi-you-should-exclude-winter-months-and-focus-on-summer-months"><i class="fa fa-check"></i><b>8.1.1</b> What is the correlation between NDVI and NDMI? - here I want you to convert the full_long dataset in to a wide dataset using the function “spread” and then make a plot that shows the correlations a function of if the site was burned or not (x axis should be ndmi) You should exclude winter months and focus on summer months</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="assignment-2.html"><a href="assignment-2.html#question-2"><i class="fa fa-check"></i><b>8.2</b> Question 2</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="assignment-2.html"><a href="assignment-2.html#what-is-the-correlation-between-average-ndsi-normalized-snow-index-for-january---april-and-average-ndvi-for-june-august-in-other-words-does-the-previous-years-snow-cover-influence-vegetation-growth-for-the-following-summer"><i class="fa fa-check"></i><b>8.2.1</b> What is the correlation between average NDSI (normalized snow index) for January - April and average NDVI for June-August? In other words, does the previous year’s snow cover influence vegetation growth for the following summer?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="assignment-2.html"><a href="assignment-2.html#question-3"><i class="fa fa-check"></i><b>8.3</b> Question 3</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="assignment-2.html"><a href="assignment-2.html#how-is-the-snow-effect-from-question-2-different-between-pre--and-post-burn-and-burned-and-unburned"><i class="fa fa-check"></i><b>8.3.1</b> How is the snow effect from question 2 different between pre- and post-burn and burned and unburned?</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="assignment-2.html"><a href="assignment-2.html#question-4"><i class="fa fa-check"></i><b>8.4</b> Question 4</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="assignment-2.html"><a href="assignment-2.html#what-month-is-the-greenest-month-on-average"><i class="fa fa-check"></i><b>8.4.1</b> What month is the greenest month on average?</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="assignment-2.html"><a href="assignment-2.html#question-5"><i class="fa fa-check"></i><b>8.5</b> Question 5</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="assignment-2.html"><a href="assignment-2.html#what-month-is-the-snowiest-on-average"><i class="fa fa-check"></i><b>8.5.1</b> What month is the snowiest on average?</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="assignment-2.html"><a href="assignment-2.html#bonus-question-1"><i class="fa fa-check"></i><b>8.6</b> Bonus Question 1</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="assignment-2.html"><a href="assignment-2.html#redo-all-problems-with-spread-and-gather-using-modern-tidyverse-syntax."><i class="fa fa-check"></i><b>8.6.1</b> Redo all problems with <code>spread</code> and <code>gather</code> using modern tidyverse syntax.</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="assignment-2.html"><a href="assignment-2.html#bonus-question-2"><i class="fa fa-check"></i><b>8.7</b> Bonus Question 2</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="assignment-2.html"><a href="assignment-2.html#use-climate-engine-to-pull-the-same-data-for-the-assignment-but-updated-with-20202021-data."><i class="fa fa-check"></i><b>8.7.1</b> Use Climate Engine to pull the same data for the assignment, but updated with 2020/2021 data.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="parts.html"><a href="parts.html"><i class="fa fa-check"></i><b>9</b> Parts</a></li>
<li class="chapter" data-level="10" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html"><i class="fa fa-check"></i><b>10</b> Simple web scraping</a>
<ul>
<li class="chapter" data-level="10.1" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#reading-an-html"><i class="fa fa-check"></i><b>10.1</b> Reading an html</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#extract-csv-links-from-webpage"><i class="fa fa-check"></i><b>10.1.1</b> Extract CSV links from webpage</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#data-download-1"><i class="fa fa-check"></i><b>10.2</b> Data Download</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#download-data-in-a-for-loop"><i class="fa fa-check"></i><b>10.2.1</b> Download data in a for loop</a></li>
<li class="chapter" data-level="10.2.2" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#download-data-in-a-map"><i class="fa fa-check"></i><b>10.2.2</b> Download data in a map</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#data-read-in"><i class="fa fa-check"></i><b>10.3</b> Data read-in</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#read-in-just-the-snow-data-as-a-loop"><i class="fa fa-check"></i><b>10.3.1</b> Read in just the snow data as a loop</a></li>
<li class="chapter" data-level="10.3.2" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#read-in-the-data-as-a-map-function"><i class="fa fa-check"></i><b>10.3.2</b> Read in the data as a map function</a></li>
<li class="chapter" data-level="10.3.3" data-path="simple-web-scraping.html"><a href="simple-web-scraping.html#plot-snow-data"><i class="fa fa-check"></i><b>10.3.3</b> Plot snow data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="assignment.html"><a href="assignment.html"><i class="fa fa-check"></i><b>11</b> Assignment:</a>
<ul>
<li class="chapter" data-level="11.1" data-path="assignment.html"><a href="assignment.html#question-1."><i class="fa fa-check"></i><b>11.1</b> Question 1.</a></li>
<li class="chapter" data-level="11.2" data-path="assignment.html"><a href="assignment.html#question-2."><i class="fa fa-check"></i><b>11.2</b> Question 2.</a></li>
<li class="chapter" data-level="11.3" data-path="assignment.html"><a href="assignment.html#question-3."><i class="fa fa-check"></i><b>11.3</b> Question 3.</a></li>
<li class="chapter" data-level="11.4" data-path="assignment.html"><a href="assignment.html#question-4."><i class="fa fa-check"></i><b>11.4</b> Question 4.</a></li>
<li class="chapter" data-level="11.5" data-path="assignment.html"><a href="assignment.html#question-5."><i class="fa fa-check"></i><b>11.5</b> Question 5.</a></li>
<li class="chapter" data-level="11.6" data-path="assignment.html"><a href="assignment.html#question-6."><i class="fa fa-check"></i><b>11.6</b> Question 6.</a></li>
<li class="chapter" data-level="11.7" data-path="assignment.html"><a href="assignment.html#bonus-question-1."><i class="fa fa-check"></i><b>11.7</b> Bonus Question 1.</a></li>
<li class="chapter" data-level="11.8" data-path="assignment.html"><a href="assignment.html#bonus-question-2."><i class="fa fa-check"></i><b>11.8</b> Bonus Question 2.</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html"><i class="fa fa-check"></i><b>12</b> Footnotes and citations</a>
<ul>
<li class="chapter" data-level="12.1" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#footnotes"><i class="fa fa-check"></i><b>12.1</b> Footnotes</a></li>
<li class="chapter" data-level="12.2" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#citations"><i class="fa fa-check"></i><b>12.2</b> Citations</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="lagos-analysis.html"><a href="lagos-analysis.html"><i class="fa fa-check"></i><b>13</b> LAGOS Analysis</a>
<ul>
<li class="chapter" data-level="13.1" data-path="lagos-analysis.html"><a href="lagos-analysis.html#loading-in-data"><i class="fa fa-check"></i><b>13.1</b> Loading in data</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="lagos-analysis.html"><a href="lagos-analysis.html#first-download-and-then-specifically-grab-the-locus-or-site-lat-longs"><i class="fa fa-check"></i><b>13.1.1</b> First download and then specifically grab the locus (or site lat longs)</a></li>
<li class="chapter" data-level="13.1.2" data-path="lagos-analysis.html"><a href="lagos-analysis.html#convert-to-spatial-data"><i class="fa fa-check"></i><b>13.1.2</b> Convert to spatial data</a></li>
<li class="chapter" data-level="13.1.3" data-path="lagos-analysis.html"><a href="lagos-analysis.html#subset-to-only-minnesota"><i class="fa fa-check"></i><b>13.1.3</b> Subset to only Minnesota</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="in-class-work.html"><a href="in-class-work.html"><i class="fa fa-check"></i><b>14</b> In-Class work</a>
<ul>
<li class="chapter" data-level="14.1" data-path="in-class-work.html"><a href="in-class-work.html#show-a-map-outline-of-iowa-and-illinois-similar-to-minnesota-map-upstream"><i class="fa fa-check"></i><b>14.1</b> 1) Show a map outline of Iowa and Illinois (similar to Minnesota map upstream)</a></li>
<li class="chapter" data-level="14.2" data-path="in-class-work.html"><a href="in-class-work.html#subset-lagos-data-to-these-sites-how-many-sites-are-in-illinois-and-iowa-combined-how-does-this-compare-to-minnesota"><i class="fa fa-check"></i><b>14.2</b> 2) Subset LAGOS data to these sites, how many sites are in Illinois and Iowa combined? How does this compare to Minnesota?</a></li>
<li class="chapter" data-level="14.3" data-path="in-class-work.html"><a href="in-class-work.html#what-is-the-distribution-of-lake-size-in-iowa-vs.-minnesota"><i class="fa fa-check"></i><b>14.3</b> 3) What is the distribution of lake size in Iowa vs. Minnesota?</a></li>
<li class="chapter" data-level="14.4" data-path="in-class-work.html"><a href="in-class-work.html#make-an-interactive-plot-of-lakes-in-iowa-and-illinois-and-color-them-by-lake-area-in-hectares"><i class="fa fa-check"></i><b>14.4</b> 4) Make an interactive plot of lakes in Iowa and Illinois and color them by lake area in hectares</a></li>
<li class="chapter" data-level="14.5" data-path="in-class-work.html"><a href="in-class-work.html#what-other-data-sources-might-we-use-to-understand-how-reservoirs-and-natural-lakes-vary-in-size-in-these-three-states"><i class="fa fa-check"></i><b>14.5</b> 5) What other data sources might we use to understand how reservoirs and natural lakes vary in size in these three states?</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="lagos-analysis-1.html"><a href="lagos-analysis-1.html"><i class="fa fa-check"></i><b>15</b> LAGOS Analysis</a>
<ul>
<li class="chapter" data-level="15.1" data-path="lagos-analysis-1.html"><a href="lagos-analysis-1.html#loading-in-data-1"><i class="fa fa-check"></i><b>15.1</b> Loading in data</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="lagos-analysis-1.html"><a href="lagos-analysis-1.html#first-download-and-then-specifically-grab-the-locus-or-site-lat-longs-1"><i class="fa fa-check"></i><b>15.1.1</b> First download and then specifically grab the locus (or site lat longs)</a></li>
<li class="chapter" data-level="15.1.2" data-path="lagos-analysis-1.html"><a href="lagos-analysis-1.html#subset-columns-nutr-to-only-keep-key-info-that-we-want"><i class="fa fa-check"></i><b>15.1.2</b> Subset columns nutr to only keep key info that we want</a></li>
<li class="chapter" data-level="15.1.3" data-path="lagos-analysis-1.html"><a href="lagos-analysis-1.html#keep-sites-with-at-least-200-observations"><i class="fa fa-check"></i><b>15.1.3</b> Keep sites with at least 200 observations</a></li>
<li class="chapter" data-level="15.1.4" data-path="lagos-analysis-1.html"><a href="lagos-analysis-1.html#join-water-quality-data-to-spatial-data"><i class="fa fa-check"></i><b>15.1.4</b> Join water quality data to spatial data</a></li>
<li class="chapter" data-level="15.1.5" data-path="lagos-analysis-1.html"><a href="lagos-analysis-1.html#mean-chl_a-map"><i class="fa fa-check"></i><b>15.1.5</b> Mean Chl_a map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="class-work.html"><a href="class-work.html"><i class="fa fa-check"></i><b>16</b> Class work</a>
<ul>
<li class="chapter" data-level="16.1" data-path="class-work.html"><a href="class-work.html#what-is-the-correlation-between-secchi-disk-depth-and-chlorophyll-a-for-sites-with-at-least-200-observations"><i class="fa fa-check"></i><b>16.1</b> 1) What is the correlation between Secchi Disk Depth and Chlorophyll a for sites with at least 200 observations?</a></li>
<li class="chapter" data-level="16.2" data-path="class-work.html"><a href="class-work.html#why-might-this-be-the-case"><i class="fa fa-check"></i><b>16.2</b> Why might this be the case?</a></li>
<li class="chapter" data-level="16.3" data-path="class-work.html"><a href="class-work.html#what-states-have-the-most-data"><i class="fa fa-check"></i><b>16.3</b> 2) What states have the most data?</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="class-work.html"><a href="class-work.html#a-first-you-will-need-to-make-a-lagos-spatial-dataset-that-has-the-total-number-of-counts-per-site."><i class="fa fa-check"></i><b>16.3.1</b> 2a) First you will need to make a lagos spatial dataset that has the total number of counts per site.</a></li>
<li class="chapter" data-level="16.3.2" data-path="class-work.html"><a href="class-work.html#b-second-you-will-need-to-join-this-point-dataset-to-the-us_boundaries-data."><i class="fa fa-check"></i><b>16.3.2</b> 2b) Second, you will need to join this point dataset to the us_boundaries data.</a></li>
<li class="chapter" data-level="16.3.3" data-path="class-work.html"><a href="class-work.html#c-then-you-will-want-to-group-by-state-and-sum-all-the-observations-in-that-state-and-arrange-that-data-from-most-to-least-total-observations-per-state."><i class="fa fa-check"></i><b>16.3.3</b> 2c) Then you will want to group by state and sum all the observations in that state and arrange that data from most to least total observations per state.</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="class-work.html"><a href="class-work.html#is-there-a-spatial-pattern-in-secchi-disk-depth-for-lakes-with-at-least-200-observations"><i class="fa fa-check"></i><b>16.4</b> 3 Is there a spatial pattern in Secchi disk depth for lakes with at least 200 observations?</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="blocks.html"><a href="blocks.html"><i class="fa fa-check"></i><b>17</b> Blocks</a>
<ul>
<li class="chapter" data-level="17.1" data-path="blocks.html"><a href="blocks.html#equations"><i class="fa fa-check"></i><b>17.1</b> Equations</a></li>
<li class="chapter" data-level="17.2" data-path="blocks.html"><a href="blocks.html#theorems-and-proofs"><i class="fa fa-check"></i><b>17.2</b> Theorems and proofs</a></li>
<li class="chapter" data-level="17.3" data-path="blocks.html"><a href="blocks.html#callout-blocks"><i class="fa fa-check"></i><b>17.3</b> Callout blocks</a></li>
<li class="chapter" data-level="17.4" data-path="blocks.html"><a href="blocks.html#weather-data-analysis"><i class="fa fa-check"></i><b>17.4</b> Weather Data Analysis</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="blocks.html"><a href="blocks.html#load-the-prism-daily-maximum-temperatures"><i class="fa fa-check"></i><b>17.4.1</b> Load the PRISM daily maximum temperatures</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="blocks.html"><a href="blocks.html#temperature-trends"><i class="fa fa-check"></i><b>17.5</b> Temperature trends</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="blocks.html"><a href="blocks.html#summer-temperature-trends-winneshiek-county"><i class="fa fa-check"></i><b>17.5.1</b> Summer temperature trends: Winneshiek County</a></li>
<li class="chapter" data-level="17.5.2" data-path="blocks.html"><a href="blocks.html#winter-temperatures---winneshiek-county"><i class="fa fa-check"></i><b>17.5.2</b> Winter Temperatures - Winneshiek County</a></li>
<li class="chapter" data-level="17.5.3" data-path="blocks.html"><a href="blocks.html#multiple-regression-quadratic-time-trend"><i class="fa fa-check"></i><b>17.5.3</b> Multiple regression – Quadratic time trend</a></li>
<li class="chapter" data-level="17.5.4" data-path="blocks.html"><a href="blocks.html#download-nass-corn-yield-data"><i class="fa fa-check"></i><b>17.5.4</b> Download NASS corn yield data</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="blocks.html"><a href="blocks.html#assignment-1"><i class="fa fa-check"></i><b>17.6</b> Assignment</a>
<ul>
<li class="chapter" data-level="17.6.1" data-path="blocks.html"><a href="blocks.html#question-1a-extract-winneshiek-county-corn-yields-fit-a-linear-time-trend-make-a-plot.-is-there-a-significant-time-trend"><i class="fa fa-check"></i><b>17.6.1</b> Question 1a: Extract Winneshiek County corn yields, fit a linear time trend, make a plot. Is there a significant time trend?</a></li>
<li class="chapter" data-level="17.6.2" data-path="blocks.html"><a href="blocks.html#question-1b-fit-a-quadratic-time-trend-i.e.-year-year2-and-make-a-plot.-is-there-evidence-for-slowing-yield-growth"><i class="fa fa-check"></i><b>17.6.2</b> Question 1b: Fit a quadratic time trend (i.e., year + year^2) and make a plot. Is there evidence for slowing yield growth?</a></li>
<li class="chapter" data-level="17.6.3" data-path="blocks.html"><a href="blocks.html#question-2-time-series-lets-analyze-the-relationship-between-temperature-and-yields-for-the-winneshiek-county-time-series.-use-data-on-yield-and-summer-avg-tmax.-is-adding-year-or-tmax2-to-your-model-helpful-make-a-plot-and-interpret-the-results."><i class="fa fa-check"></i><b>17.6.3</b> Question 2 – Time Series: Let’s analyze the relationship between temperature and yields for the Winneshiek County time series. Use data on yield and summer avg Tmax. Is adding year or Tmax^2 to your model helpful? Make a plot and interpret the results.</a></li>
<li class="chapter" data-level="17.6.4" data-path="blocks.html"><a href="blocks.html#question-3-cross-section-analyze-the-relationship-between-temperature-and-yield-across-all-counties-in-2018.-is-there-a-relationship-interpret-the-results."><i class="fa fa-check"></i><b>17.6.4</b> Question 3 – Cross-Section: Analyze the relationship between temperature and yield across all counties in 2018. Is there a relationship? Interpret the results.</a></li>
<li class="chapter" data-level="17.6.5" data-path="blocks.html"><a href="blocks.html#question-4-panel-one-way-to-leverage-multiple-time-series-is-to-group-all-data-into-what-is-called-a-panel-regression.-convert-the-county-id-code-countyfp-or-county_ansi-into-factor-using-as.factor-then-include-this-variable-in-a-regression-using-all-counties-yield-and-summer-temperature-data.-how-does-the-significance-of-your-temperature-coefficients-tmax-tmax2-change-make-a-plot-comparing-actual-and-fitted-yields-and-interpret-the-results-of-your-model."><i class="fa fa-check"></i><b>17.6.5</b> Question 4 – Panel: One way to leverage multiple time series is to group all data into what is called a “panel” regression. Convert the county ID code (“countyfp” or “county_ansi”) into factor using as.factor, then include this variable in a regression using all counties’ yield and summer temperature data. How does the significance of your temperature coefficients (Tmax, Tmax^2) change? Make a plot comparing actual and fitted yields and interpret the results of your model.</a></li>
<li class="chapter" data-level="17.6.6" data-path="blocks.html"><a href="blocks.html#question-5-soybeans-download-nass-data-on-soybean-yields-and-explore-either-a-time-series-relationship-for-a-given-county-the-cross-sectional-relationship-for-a-given-year-or-a-panel-across-all-counties-and-years."><i class="fa fa-check"></i><b>17.6.6</b> Question 5 – Soybeans: Download NASS data on soybean yields and explore either a time series relationship for a given county, the <strong>cross-sectional relationship for a given year</strong>, or a panel across all counties and years.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="sharing-your-book.html"><a href="sharing-your-book.html"><i class="fa fa-check"></i><b>18</b> Sharing your book</a>
<ul>
<li class="chapter" data-level="18.1" data-path="sharing-your-book.html"><a href="sharing-your-book.html#publishing"><i class="fa fa-check"></i><b>18.1</b> Publishing</a></li>
<li class="chapter" data-level="18.2" data-path="sharing-your-book.html"><a href="sharing-your-book.html#pages"><i class="fa fa-check"></i><b>18.2</b> 404 pages</a></li>
<li class="chapter" data-level="18.3" data-path="sharing-your-book.html"><a href="sharing-your-book.html#metadata-for-sharing"><i class="fa fa-check"></i><b>18.3</b> Metadata for sharing</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>19</b> Intro</a>
<ul>
<li class="chapter" data-level="19.1" data-path="intro.html"><a href="intro.html#data-read"><i class="fa fa-check"></i><b>19.1</b> Data read</a></li>
<li class="chapter" data-level="19.2" data-path="intro.html"><a href="intro.html#model-development"><i class="fa fa-check"></i><b>19.2</b> Model development</a></li>
<li class="chapter" data-level="19.3" data-path="intro.html"><a href="intro.html#chl-a-model"><i class="fa fa-check"></i><b>19.3</b> Chl-a model</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="intro.html"><a href="intro.html#chl-a-model-measuredpredicted-plot"><i class="fa fa-check"></i><b>19.3.1</b> Chl-a Model Measured/Predicted Plot</a></li>
<li class="chapter" data-level="19.3.2" data-path="intro.html"><a href="intro.html#chl-a-error-metrics"><i class="fa fa-check"></i><b>19.3.2</b> Chl-a Error Metrics</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="intro.html"><a href="intro.html#tss-model"><i class="fa fa-check"></i><b>19.4</b> TSS Model</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="intro.html"><a href="intro.html#tss-plot"><i class="fa fa-check"></i><b>19.4.1</b> TSS plot</a></li>
<li class="chapter" data-level="19.4.2" data-path="intro.html"><a href="intro.html#tss-evaluation"><i class="fa fa-check"></i><b>19.4.2</b> TSS Evaluation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="q1-what-is-the-best-chla-rmse-you-could-get-after-50-minutes-of-fiddling.html"><a href="q1-what-is-the-best-chla-rmse-you-could-get-after-50-minutes-of-fiddling.html"><i class="fa fa-check"></i><b>20</b> Q1) What is the best CHLA RMSE you could get after 50 minutes of fiddling?</a></li>
<li class="chapter" data-level="21" data-path="q2-what-is-the-best-tss-rmse-you-could-get-after-50-minutes-of-fiddling.html"><a href="q2-what-is-the-best-tss-rmse-you-could-get-after-50-minutes-of-fiddling.html"><i class="fa fa-check"></i><b>21</b> Q2) What is the best TSS RMSE you could get after 50 minutes of fiddling?</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SOCR 580A7 Bookdown Portfolio</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="blocks" class="section level1" number="17">
<h1><span class="header-section-number">Chapter 17</span> Blocks</h1>
<div id="equations" class="section level2" number="17.1">
<h2><span class="header-section-number">17.1</span> Equations</h2>
<p>Here is an equation.</p>
<p><span class="math display" id="eq:binom">\[\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  \tag{17.1}
\end{equation}\]</span></p>
<p>You may refer to using <code>\@ref(eq:binom)</code>, like see Equation <a href="blocks.html#eq:binom">(17.1)</a>.</p>
</div>
<div id="theorems-and-proofs" class="section level2" number="17.2">
<h2><span class="header-section-number">17.2</span> Theorems and proofs</h2>
<p>Labeled theorems can be referenced in text using <code>\@ref(thm:tri)</code>, for example, check out this smart theorem <a href="blocks.html#thm:tri">17.1</a>.</p>
<div class="theorem">
<p><span id="thm:tri" class="theorem"><strong>Theorem 17.1  </strong></span>For a right triangle, if <span class="math inline">\(c\)</span> denotes the <em>length</em> of the hypotenuse
and <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> denote the lengths of the <strong>other</strong> two sides, we have
<span class="math display">\[a^2 + b^2 = c^2\]</span></p>
</div>
<p>Read more here <a href="https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html" class="uri">https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html</a>.</p>
</div>
<div id="callout-blocks" class="section level2" number="17.3">
<h2><span class="header-section-number">17.3</span> Callout blocks</h2>
<p>The R Markdown Cookbook provides more help on how to use custom blocks to design your own callouts: <a href="https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html" class="uri">https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html</a></p>
<p>title: “Weather and Corn Yield Regressions”</p>
</div>
<div id="weather-data-analysis" class="section level2" number="17.4">
<h2><span class="header-section-number">17.4</span> Weather Data Analysis</h2>
<div id="load-the-prism-daily-maximum-temperatures" class="section level3" number="17.4.1">
<h3><span class="header-section-number">17.4.1</span> Load the PRISM daily maximum temperatures</h3>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="blocks.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># daily max temperature</span></span>
<span id="cb73-2"><a href="blocks.html#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dimensions: counties x days x years</span></span>
<span id="cb73-3"><a href="blocks.html#cb73-3" aria-hidden="true" tabindex="-1"></a>prism <span class="ot">&lt;-</span> <span class="fu">readMat</span>(<span class="st">&quot;data/prismiowa.mat&quot;</span>)</span>
<span id="cb73-4"><a href="blocks.html#cb73-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-5"><a href="blocks.html#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="co"># look at county #1</span></span>
<span id="cb73-6"><a href="blocks.html#cb73-6" aria-hidden="true" tabindex="-1"></a>t_1981_c1 <span class="ot">&lt;-</span> prism<span class="sc">$</span>tmaxdaily.iowa[<span class="dv">1</span>,,<span class="dv">1</span>]</span>
<span id="cb73-7"><a href="blocks.html#cb73-7" aria-hidden="true" tabindex="-1"></a>t_1981_c1[<span class="dv">366</span>]</span></code></pre></div>
<pre><code>## [1] NaN</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="blocks.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">366</span>, t_1981_c1, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/tmax%20data-1.png" width="672" /></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="blocks.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb76-2"><a href="blocks.html#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">366</span>, <span class="at">y =</span> t_1981_c1)) <span class="sc">+</span></span>
<span id="cb76-3"><a href="blocks.html#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb76-4"><a href="blocks.html#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;day of year&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-5"><a href="blocks.html#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;daily maximum temperature (°C)&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-6"><a href="blocks.html#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Daily Maximum Temperature, Iowa County #1&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 row(s) containing missing values (geom_path).</code></pre>
<p><img src="_main_files/figure-html/tmax%20data-2.png" width="672" /></p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="blocks.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assign dimension names to tmax matrix</span></span>
<span id="cb78-2"><a href="blocks.html#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(prism<span class="sc">$</span>tmaxdaily.iowa) <span class="ot">&lt;-</span> <span class="fu">list</span>(prism<span class="sc">$</span>COUNTYFP, <span class="dv">1</span><span class="sc">:</span><span class="dv">366</span>, prism<span class="sc">$</span>years)</span>
<span id="cb78-3"><a href="blocks.html#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="co">#wants a list corresponding to different dimensions - first dim is county code (FP code)</span></span>
<span id="cb78-4"><a href="blocks.html#cb78-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-5"><a href="blocks.html#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="co"># converted 3d matrix into a data frame</span></span>
<span id="cb78-6"><a href="blocks.html#cb78-6" aria-hidden="true" tabindex="-1"></a>tmaxdf <span class="ot">&lt;-</span> <span class="fu">as.data.frame.table</span>(prism<span class="sc">$</span>tmaxdaily.iowa)</span>
<span id="cb78-7"><a href="blocks.html#cb78-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-8"><a href="blocks.html#cb78-8" aria-hidden="true" tabindex="-1"></a><span class="co"># relabel the columns</span></span>
<span id="cb78-9"><a href="blocks.html#cb78-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tmaxdf) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;countyfp&quot;</span>,<span class="st">&quot;doy&quot;</span>,<span class="st">&quot;year&quot;</span>,<span class="st">&quot;tmax&quot;</span>)</span>
<span id="cb78-10"><a href="blocks.html#cb78-10" aria-hidden="true" tabindex="-1"></a>tmaxdf <span class="ot">&lt;-</span> <span class="fu">tibble</span>(tmaxdf)</span></code></pre></div>
</div>
</div>
<div id="temperature-trends" class="section level2" number="17.5">
<h2><span class="header-section-number">17.5</span> Temperature trends</h2>
<div id="summer-temperature-trends-winneshiek-county" class="section level3" number="17.5.1">
<h3><span class="header-section-number">17.5.1</span> Summer temperature trends: Winneshiek County</h3>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="blocks.html#cb79-1" aria-hidden="true" tabindex="-1"></a>tmaxdf<span class="sc">$</span>doy <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(tmaxdf<span class="sc">$</span>doy)</span>
<span id="cb79-2"><a href="blocks.html#cb79-2" aria-hidden="true" tabindex="-1"></a>tmaxdf<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(tmaxdf<span class="sc">$</span>year))</span>
<span id="cb79-3"><a href="blocks.html#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="blocks.html#cb79-4" aria-hidden="true" tabindex="-1"></a>winnesummer <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb79-5"><a href="blocks.html#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(countyfp<span class="sc">==</span><span class="dv">191</span> <span class="sc">&amp;</span> doy <span class="sc">&gt;=</span> <span class="dv">152</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;=</span> <span class="dv">243</span>) <span class="sc">%&gt;%</span></span>
<span id="cb79-6"><a href="blocks.html#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb79-7"><a href="blocks.html#cb79-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax))</span>
<span id="cb79-8"><a href="blocks.html#cb79-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-9"><a href="blocks.html#cb79-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnesummer, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> meantmax)) <span class="sc">+</span></span>
<span id="cb79-10"><a href="blocks.html#cb79-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb79-11"><a href="blocks.html#cb79-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb79-12"><a href="blocks.html#cb79-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tmax (°C)&quot;</span>) <span class="sc">+</span></span>
<span id="cb79-13"><a href="blocks.html#cb79-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/temp%20trends-1.png" width="672" /></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="blocks.html#cb81-1" aria-hidden="true" tabindex="-1"></a>lm_summertmax <span class="ot">&lt;-</span> <span class="fu">lm</span>(meantmax <span class="sc">~</span> year, winnesummer)</span>
<span id="cb81-2"><a href="blocks.html#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summertmax)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meantmax ~ year, data = winnesummer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.5189 -0.7867 -0.0341  0.6859  3.7415 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 41.57670   36.44848   1.141    0.262
## year        -0.00747    0.01823  -0.410    0.684
## 
## Residual standard error: 1.232 on 36 degrees of freedom
## Multiple R-squared:  0.004644,   Adjusted R-squared:  -0.02301 
## F-statistic: 0.168 on 1 and 36 DF,  p-value: 0.6844</code></pre>
</div>
<div id="winter-temperatures---winneshiek-county" class="section level3" number="17.5.2">
<h3><span class="header-section-number">17.5.2</span> Winter Temperatures - Winneshiek County</h3>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="blocks.html#cb83-1" aria-hidden="true" tabindex="-1"></a>winnewinter <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="blocks.html#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(countyfp<span class="sc">==</span><span class="dv">191</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;=</span> <span class="dv">59</span> <span class="sc">|</span> doy <span class="sc">&gt;=</span> <span class="dv">335</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(tmax)) <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="blocks.html#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb83-4"><a href="blocks.html#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax))</span>
<span id="cb83-5"><a href="blocks.html#cb83-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-6"><a href="blocks.html#cb83-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnewinter, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> meantmax)) <span class="sc">+</span></span>
<span id="cb83-7"><a href="blocks.html#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb83-8"><a href="blocks.html#cb83-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb83-9"><a href="blocks.html#cb83-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tmax (°C)&quot;</span>) <span class="sc">+</span></span>
<span id="cb83-10"><a href="blocks.html#cb83-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<p><img src="_main_files/figure-html/winter%20temps-1.png" width="672" /></p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="blocks.html#cb84-1" aria-hidden="true" tabindex="-1"></a>lm_wintertmax <span class="ot">&lt;-</span> <span class="fu">lm</span>(meantmax <span class="sc">~</span> year, winnewinter)</span>
<span id="cb84-2"><a href="blocks.html#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_wintertmax)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meantmax ~ year, data = winnewinter)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.0748 -2.6494  0.7715  2.2172  4.1361 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -119.10546   94.08124  -1.266    0.214
## year           0.05960    0.04705   1.267    0.213
## 
## Residual standard error: 3.181 on 36 degrees of freedom
## Multiple R-squared:  0.04267,    Adjusted R-squared:  0.01608 
## F-statistic: 1.605 on 1 and 36 DF,  p-value: 0.2134</code></pre>
</div>
<div id="multiple-regression-quadratic-time-trend" class="section level3" number="17.5.3">
<h3><span class="header-section-number">17.5.3</span> Multiple regression – Quadratic time trend</h3>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="blocks.html#cb86-1" aria-hidden="true" tabindex="-1"></a>winnewinter<span class="sc">$</span>yearsq <span class="ot">&lt;-</span> winnewinter<span class="sc">$</span>year<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb86-2"><a href="blocks.html#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="blocks.html#cb86-3" aria-hidden="true" tabindex="-1"></a>lm_wintertmaxquad <span class="ot">&lt;-</span> <span class="fu">lm</span>(meantmax <span class="sc">~</span> year <span class="sc">+</span> yearsq, winnewinter)</span>
<span id="cb86-4"><a href="blocks.html#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_wintertmaxquad)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meantmax ~ year + yearsq, data = winnewinter)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.680 -2.813  0.640  2.264  4.072 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.049e+04  1.939e+04  -0.541    0.592
## year         1.043e+01  1.940e+01   0.538    0.594
## yearsq      -2.594e-03  4.851e-03  -0.535    0.596
## 
## Residual standard error: 3.213 on 35 degrees of freedom
## Multiple R-squared:  0.05043,    Adjusted R-squared:  -0.003832 
## F-statistic: 0.9294 on 2 and 35 DF,  p-value: 0.4043</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="blocks.html#cb88-1" aria-hidden="true" tabindex="-1"></a>winnewinter<span class="sc">$</span>fitted <span class="ot">&lt;-</span> lm_wintertmaxquad<span class="sc">$</span>fitted.values</span>
<span id="cb88-2"><a href="blocks.html#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="blocks.html#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnewinter) <span class="sc">+</span></span>
<span id="cb88-4"><a href="blocks.html#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> meantmax)) <span class="sc">+</span></span>
<span id="cb88-5"><a href="blocks.html#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> fitted)) <span class="sc">+</span></span>
<span id="cb88-6"><a href="blocks.html#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb88-7"><a href="blocks.html#cb88-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;tmax&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/quadratic%20temp%20trend-1.png" width="672" /></p>
</div>
<div id="download-nass-corn-yield-data" class="section level3" number="17.5.4">
<h3><span class="header-section-number">17.5.4</span> Download NASS corn yield data</h3>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="blocks.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set our API key with NASS</span></span>
<span id="cb89-2"><a href="blocks.html#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nassqs_auth</span>(<span class="at">key =</span> <span class="st">&quot;08EB8353-3696-30D9-96D4-839C4DEA18B4&quot;</span>)</span>
<span id="cb89-3"><a href="blocks.html#cb89-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-4"><a href="blocks.html#cb89-4" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters to query on </span></span>
<span id="cb89-5"><a href="blocks.html#cb89-5" aria-hidden="true" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">commodity_desc =</span> <span class="st">&quot;CORN&quot;</span>, <span class="at">util_practice_desc =</span> <span class="st">&quot;GRAIN&quot;</span>, <span class="at">prodn_practice_desc =</span> <span class="st">&quot;ALL PRODUCTION PRACTICES&quot;</span>, <span class="at">year__GE =</span> <span class="dv">1981</span>, <span class="at">state_alpha =</span> <span class="st">&quot;IA&quot;</span>)</span>
<span id="cb89-6"><a href="blocks.html#cb89-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-7"><a href="blocks.html#cb89-7" aria-hidden="true" tabindex="-1"></a><span class="co"># download</span></span>
<span id="cb89-8"><a href="blocks.html#cb89-8" aria-hidden="true" tabindex="-1"></a>cornyieldsall <span class="ot">&lt;-</span> <span class="fu">nassqs_yields</span>(params)</span>
<span id="cb89-9"><a href="blocks.html#cb89-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-10"><a href="blocks.html#cb89-10" aria-hidden="true" tabindex="-1"></a>cornyieldsall<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(cornyieldsall<span class="sc">$</span>county_ansi)</span>
<span id="cb89-11"><a href="blocks.html#cb89-11" aria-hidden="true" tabindex="-1"></a>cornyieldsall<span class="sc">$</span>yield <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(cornyieldsall<span class="sc">$</span>Value)</span>
<span id="cb89-12"><a href="blocks.html#cb89-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-13"><a href="blocks.html#cb89-13" aria-hidden="true" tabindex="-1"></a><span class="co"># clean and filter this dataset</span></span>
<span id="cb89-14"><a href="blocks.html#cb89-14" aria-hidden="true" tabindex="-1"></a>cornyields <span class="ot">&lt;-</span> <span class="fu">select</span>(cornyieldsall, county_ansi, county_name, yield, year) <span class="sc">%&gt;%</span></span>
<span id="cb89-15"><a href="blocks.html#cb89-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_ansi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(yield))</span>
<span id="cb89-16"><a href="blocks.html#cb89-16" aria-hidden="true" tabindex="-1"></a>cornyields <span class="ot">&lt;-</span> <span class="fu">tibble</span>(cornyields)</span></code></pre></div>
</div>
</div>
<div id="assignment-1" class="section level2" number="17.6">
<h2><span class="header-section-number">17.6</span> Assignment</h2>
<div id="question-1a-extract-winneshiek-county-corn-yields-fit-a-linear-time-trend-make-a-plot.-is-there-a-significant-time-trend" class="section level3" number="17.6.1">
<h3><span class="header-section-number">17.6.1</span> Question 1a: Extract Winneshiek County corn yields, fit a linear time trend, make a plot. Is there a significant time trend?</h3>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="blocks.html#cb90-1" aria-hidden="true" tabindex="-1"></a>winnecorn <span class="ot">&lt;-</span> cornyields <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="blocks.html#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(county_ansi<span class="sc">==</span><span class="dv">191</span>)</span>
<span id="cb90-3"><a href="blocks.html#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="blocks.html#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnecorn, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb90-5"><a href="blocks.html#cb90-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb90-6"><a href="blocks.html#cb90-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Winneshiek Corn Yield over Time&quot;</span>) <span class="sc">+</span></span>
<span id="cb90-7"><a href="blocks.html#cb90-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb90-8"><a href="blocks.html#cb90-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="blocks.html#cb91-1" aria-hidden="true" tabindex="-1"></a>lm_winnecorn <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> year, winnecorn)</span>
<span id="cb91-2"><a href="blocks.html#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_winnecorn)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ year, data = winnecorn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -51.163  -1.841   2.363   9.437  24.376 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4763.290    448.286  -10.63 4.46e-13 ***
## year            2.457      0.224   10.96 1.77e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.97 on 39 degrees of freedom
## Multiple R-squared:  0.7551, Adjusted R-squared:  0.7488 
## F-statistic: 120.2 on 1 and 39 DF,  p-value: 1.767e-13</code></pre>
<p>From our linear model, we can see that there is a significant time trend. The p value for the year is less than alpha = 0.05. This agrees with the graph showing the yield data following the linear model line in a positive slope. With increasing years, there is a concomitant increase in yield.</p>
</div>
<div id="question-1b-fit-a-quadratic-time-trend-i.e.-year-year2-and-make-a-plot.-is-there-evidence-for-slowing-yield-growth" class="section level3" number="17.6.2">
<h3><span class="header-section-number">17.6.2</span> Question 1b: Fit a quadratic time trend (i.e., year + year^2) and make a plot. Is there evidence for slowing yield growth?</h3>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="blocks.html#cb93-1" aria-hidden="true" tabindex="-1"></a>winnecorn<span class="sc">$</span>yearsq <span class="ot">&lt;-</span> winnecorn<span class="sc">$</span>year<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb93-2"><a href="blocks.html#cb93-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-3"><a href="blocks.html#cb93-3" aria-hidden="true" tabindex="-1"></a>lm_winnecornquad <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> year <span class="sc">+</span> yearsq, winnecorn)</span>
<span id="cb93-4"><a href="blocks.html#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_winnecornquad)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ year + yearsq, data = winnecorn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -51.384  -3.115   1.388   9.743  25.324 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  2.583e+04  8.580e+04   0.301    0.765
## year        -2.812e+01  8.576e+01  -0.328    0.745
## yearsq       7.641e-03  2.143e-02   0.357    0.723
## 
## Residual standard error: 17.17 on 38 degrees of freedom
## Multiple R-squared:  0.7559, Adjusted R-squared:  0.7431 
## F-statistic: 58.84 on 2 and 38 DF,  p-value: 2.311e-12</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="blocks.html#cb95-1" aria-hidden="true" tabindex="-1"></a>winnecorn<span class="sc">$</span>fitted <span class="ot">&lt;-</span> lm_winnecornquad<span class="sc">$</span>fitted.values</span>
<span id="cb95-2"><a href="blocks.html#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="blocks.html#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnecorn) <span class="sc">+</span></span>
<span id="cb95-4"><a href="blocks.html#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb95-5"><a href="blocks.html#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> fitted)) <span class="sc">+</span></span>
<span id="cb95-6"><a href="blocks.html#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb95-7"><a href="blocks.html#cb95-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Quadratic Time Trend for Corn Yield&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="blocks.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(winnecorn) <span class="sc">+</span></span>
<span id="cb96-2"><a href="blocks.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb96-3"><a href="blocks.html#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> fitted), <span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb96-4"><a href="blocks.html#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb96-5"><a href="blocks.html#cb96-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Quadratic Time Trend for Corn Yield&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-53-2.png" width="672" /></p>
<p>There is not sufficient evidence for slowing yield growth. The year squared estimate is positive and the year is negative, indicating that yield growth is not slowing. The p values for the individual estimates are also greater than alpha = 0.05.</p>
</div>
<div id="question-2-time-series-lets-analyze-the-relationship-between-temperature-and-yields-for-the-winneshiek-county-time-series.-use-data-on-yield-and-summer-avg-tmax.-is-adding-year-or-tmax2-to-your-model-helpful-make-a-plot-and-interpret-the-results." class="section level3" number="17.6.3">
<h3><span class="header-section-number">17.6.3</span> Question 2 – Time Series: Let’s analyze the relationship between temperature and yields for the Winneshiek County time series. Use data on yield and summer avg Tmax. Is adding year or Tmax^2 to your model helpful? Make a plot and interpret the results.</h3>
<p>Combine data for yield and temperature in Winneshiek County:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="blocks.html#cb97-1" aria-hidden="true" tabindex="-1"></a>summercorn <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(winnecorn,winnesummer, <span class="at">by =</span> <span class="st">&#39;year&#39;</span>)</span>
<span id="cb97-2"><a href="blocks.html#cb97-2" aria-hidden="true" tabindex="-1"></a>summercorn<span class="sc">$</span>meantmaxsq <span class="ot">&lt;-</span> summercorn<span class="sc">$</span>meantmax<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<p>Make linear regression models with the different parameters of interest:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="blocks.html#cb98-1" aria-hidden="true" tabindex="-1"></a>lm_summercorn_single <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax, summercorn)</span>
<span id="cb98-2"><a href="blocks.html#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summercorn_single)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax, data = summercorn)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -71.96 -19.85  -3.19  24.64  61.72 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  275.876    118.335   2.331   0.0255 *
## meantmax      -4.763      4.438  -1.073   0.2902  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 32.88 on 36 degrees of freedom
## Multiple R-squared:  0.03101,    Adjusted R-squared:  0.004098 
## F-statistic: 1.152 on 1 and 36 DF,  p-value: 0.2902</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="blocks.html#cb100-1" aria-hidden="true" tabindex="-1"></a>summercorn<span class="sc">$</span>fittedsingle <span class="ot">&lt;-</span> lm_summercorn_single<span class="sc">$</span>fitted.values</span>
<span id="cb100-2"><a href="blocks.html#cb100-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-3"><a href="blocks.html#cb100-3" aria-hidden="true" tabindex="-1"></a>lm_summercorn_quad <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax <span class="sc">+</span> meantmaxsq, summercorn)</span>
<span id="cb100-4"><a href="blocks.html#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summercorn_quad)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax + meantmaxsq, data = summercorn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -56.587 -22.262  -0.982  22.409  52.798 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) -4223.604   1446.639  -2.920  0.00609 **
## meantmax      328.918    107.068   3.072  0.00410 **
## meantmaxsq     -6.173      1.979  -3.119  0.00362 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 29.5 on 35 degrees of freedom
## Multiple R-squared:  0.2417, Adjusted R-squared:  0.1984 
## F-statistic: 5.579 on 2 and 35 DF,  p-value: 0.007887</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="blocks.html#cb102-1" aria-hidden="true" tabindex="-1"></a>summercorn<span class="sc">$</span>fittedquad <span class="ot">&lt;-</span> lm_summercorn_quad<span class="sc">$</span>fitted.values</span>
<span id="cb102-2"><a href="blocks.html#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="blocks.html#cb102-3" aria-hidden="true" tabindex="-1"></a>lm_summercorn_year <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax <span class="sc">+</span> year, summercorn)</span>
<span id="cb102-4"><a href="blocks.html#cb102-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summercorn_year)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax + year, data = summercorn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -53.071  -7.269   2.271   9.935  27.505 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4791.774    513.812  -9.326 5.10e-11 ***
## meantmax       -3.201      2.308  -1.387    0.174    
## year            2.514      0.253   9.934 1.01e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 17.06 on 35 degrees of freedom
## Multiple R-squared:  0.7463, Adjusted R-squared:  0.7318 
## F-statistic: 51.48 on 2 and 35 DF,  p-value: 3.761e-11</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="blocks.html#cb104-1" aria-hidden="true" tabindex="-1"></a>summercorn<span class="sc">$</span>fittedyear <span class="ot">&lt;-</span> lm_summercorn_year<span class="sc">$</span>fitted.values</span>
<span id="cb104-2"><a href="blocks.html#cb104-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-3"><a href="blocks.html#cb104-3" aria-hidden="true" tabindex="-1"></a>lm_summercorn <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax <span class="sc">+</span> year <span class="sc">+</span> meantmaxsq, summercorn)</span>
<span id="cb104-4"><a href="blocks.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summercorn)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax + year + meantmaxsq, data = summercorn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -44.683  -5.427   1.214   8.943  25.127 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -7280.2956   755.2808  -9.639 2.96e-11 ***
## meantmax      208.9004    52.9773   3.943 0.000381 ***
## year            2.3286     0.2166  10.752 1.77e-12 ***
## meantmaxsq     -3.9259     0.9799  -4.006 0.000318 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.27 on 34 degrees of freedom
## Multiple R-squared:  0.8277, Adjusted R-squared:  0.8125 
## F-statistic: 54.43 on 3 and 34 DF,  p-value: 4.538e-13</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="blocks.html#cb106-1" aria-hidden="true" tabindex="-1"></a>summercorn<span class="sc">$</span>fitted <span class="ot">&lt;-</span> lm_summercorn<span class="sc">$</span>fitted.values</span></code></pre></div>
<p>Plot the linear model results</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="blocks.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summercorn) <span class="sc">+</span></span>
<span id="cb107-2"><a href="blocks.html#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb107-3"><a href="blocks.html#cb107-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fittedsingle)) <span class="sc">+</span></span>
<span id="cb107-4"><a href="blocks.html#cb107-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb107-5"><a href="blocks.html#cb107-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fittedsingle), <span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb107-6"><a href="blocks.html#cb107-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Corn Yield and Mean Maximum Summer Temperature&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="blocks.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summercorn) <span class="sc">+</span></span>
<span id="cb108-2"><a href="blocks.html#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb108-3"><a href="blocks.html#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fittedquad)) <span class="sc">+</span></span>
<span id="cb108-4"><a href="blocks.html#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb108-5"><a href="blocks.html#cb108-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Quadratic Temperature Trend for Corn Yield&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-2.png" width="672" /></p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="blocks.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summercorn) <span class="sc">+</span></span>
<span id="cb109-2"><a href="blocks.html#cb109-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb109-3"><a href="blocks.html#cb109-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb109-4"><a href="blocks.html#cb109-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fittedquad), <span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb109-5"><a href="blocks.html#cb109-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Quadratic Temperature Trend for Corn Yield&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-3.png" width="672" /></p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="blocks.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summercorn) <span class="sc">+</span></span>
<span id="cb110-2"><a href="blocks.html#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb110-3"><a href="blocks.html#cb110-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fittedyear),<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb110-4"><a href="blocks.html#cb110-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb110-5"><a href="blocks.html#cb110-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Years and Max Temperature as Corn Yield Predictors&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-4.png" width="672" /></p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="blocks.html#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summercorn) <span class="sc">+</span></span>
<span id="cb111-2"><a href="blocks.html#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb111-3"><a href="blocks.html#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fitted),<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb111-4"><a href="blocks.html#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb111-5"><a href="blocks.html#cb111-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Years, Max Temperature, and Quadratic Temperature as Corn Yield Predictors&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-5.png" width="672" /></p>
<p>Adding tmax^2 and year is helpful to the model. From the simple linear regression, we saw that the R-squared value is 0.03101, indicating that the mean max temperature observation only explains 3.101% of the variability in yield. When tmax^2 was added, the R-squared value increased to 0.1984. When year was added, R-sqaured increased to 0.7318. When year and tmax^2 are added, the R-squared value changed to 0.8125, indicating that 81.25% of the variation within yield is explained by all predictors. These results suggest that adding year and tmax^2 make a stronger model.</p>
<p>The estimate for mean max temperature squared is negative, indicating that temperature change is slowing. With increasing maximum temperature, there is a decrease in yield. With increasing years, there is an increase in corn yield.</p>
</div>
<div id="question-3-cross-section-analyze-the-relationship-between-temperature-and-yield-across-all-counties-in-2018.-is-there-a-relationship-interpret-the-results." class="section level3" number="17.6.4">
<h3><span class="header-section-number">17.6.4</span> Question 3 – Cross-Section: Analyze the relationship between temperature and yield across all counties in 2018. Is there a relationship? Interpret the results.</h3>
<p>Select data from 2018 and combine yield and temperature data:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="blocks.html#cb112-1" aria-hidden="true" tabindex="-1"></a>yield <span class="ot">&lt;-</span> cornyieldsall <span class="sc">%&gt;%</span> </span>
<span id="cb112-2"><a href="blocks.html#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2018</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb112-3"><a href="blocks.html#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county_name) <span class="sc">%&gt;%</span> </span>
<span id="cb112-4"><a href="blocks.html#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb112-5"><a href="blocks.html#cb112-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_ansi))</span>
<span id="cb112-6"><a href="blocks.html#cb112-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-7"><a href="blocks.html#cb112-7" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb112-8"><a href="blocks.html#cb112-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(countyfp) <span class="sc">%&gt;%</span></span>
<span id="cb112-9"><a href="blocks.html#cb112-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2018</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb112-10"><a href="blocks.html#cb112-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(doy <span class="sc">&gt;=</span> <span class="dv">152</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;=</span> <span class="dv">243</span>) <span class="sc">%&gt;%</span></span>
<span id="cb112-11"><a href="blocks.html#cb112-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax)) <span class="sc">%&gt;%</span> </span>
<span id="cb112-12"><a href="blocks.html#cb112-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">county_ansi =</span> <span class="st">&quot;countyfp&quot;</span>)</span>
<span id="cb112-13"><a href="blocks.html#cb112-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-14"><a href="blocks.html#cb112-14" aria-hidden="true" tabindex="-1"></a>temp<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(temp<span class="sc">$</span>county_ansi))</span>
<span id="cb112-15"><a href="blocks.html#cb112-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-16"><a href="blocks.html#cb112-16" aria-hidden="true" tabindex="-1"></a>summeryield <span class="ot">&lt;-</span> <span class="fu">left_join</span>(yield, temp, <span class="at">by=</span><span class="st">&#39;county_ansi&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb112-17"><a href="blocks.html#cb112-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., county_ansi, county_name, yield, meantmax)</span></code></pre></div>
<p>Fit a simple and multiple regression model:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="blocks.html#cb113-1" aria-hidden="true" tabindex="-1"></a>lm_summeryield <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax, summeryield)</span>
<span id="cb113-2"><a href="blocks.html#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summeryield)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax, data = summeryield)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.983 -15.041   0.955  16.795  31.999 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  312.466     63.387   4.929 3.69e-06 ***
## meantmax      -4.216      2.241  -1.882   0.0631 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.64 on 91 degrees of freedom
## Multiple R-squared:  0.03745,    Adjusted R-squared:  0.02687 
## F-statistic: 3.541 on 1 and 91 DF,  p-value: 0.06308</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="blocks.html#cb115-1" aria-hidden="true" tabindex="-1"></a>summeryield<span class="sc">$</span>meantmaxsq <span class="ot">&lt;-</span> summeryield<span class="sc">$</span>meantmax<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb115-2"><a href="blocks.html#cb115-2" aria-hidden="true" tabindex="-1"></a>lm_summeryield_quad <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax <span class="sc">+</span> meantmaxsq, summeryield)</span>
<span id="cb115-3"><a href="blocks.html#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summeryield_quad)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax + meantmaxsq, data = summeryield)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -44.221 -15.399   5.007  14.541  30.879 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) -5501.602   1860.830  -2.957  0.00397 **
## meantmax      406.789    131.493   3.094  0.00263 **
## meantmaxsq     -7.256      2.321  -3.126  0.00239 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.75 on 90 degrees of freedom
## Multiple R-squared:  0.1317, Adjusted R-squared:  0.1124 
## F-statistic: 6.827 on 2 and 90 DF,  p-value: 0.001736</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="blocks.html#cb117-1" aria-hidden="true" tabindex="-1"></a>summeryield<span class="sc">$</span>fitted <span class="ot">&lt;-</span> lm_summeryield_quad<span class="sc">$</span>fitted.values</span></code></pre></div>
<p>Plot results of models:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="blocks.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summeryield, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb118-2"><a href="blocks.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb118-3"><a href="blocks.html#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Corn Yield and Mean Maximum Summer Temperature in 2018&quot;</span>) <span class="sc">+</span></span>
<span id="cb118-4"><a href="blocks.html#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb118-5"><a href="blocks.html#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="blocks.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summeryield) <span class="sc">+</span></span>
<span id="cb119-2"><a href="blocks.html#cb119-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb119-3"><a href="blocks.html#cb119-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fitted)) <span class="sc">+</span></span>
<span id="cb119-4"><a href="blocks.html#cb119-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb119-5"><a href="blocks.html#cb119-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Quadratic Temperature Trend for Corn Yield in 2018&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-2.png" width="672" /></p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="blocks.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summeryield) <span class="sc">+</span></span>
<span id="cb120-2"><a href="blocks.html#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb120-3"><a href="blocks.html#cb120-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fitted), <span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb120-4"><a href="blocks.html#cb120-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb120-5"><a href="blocks.html#cb120-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Quadratic Temperature Trend for Corn Yield in 2018&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-3.png" width="672" /></p>
<p>From the graph of temperature and yield across all counties, we can see that there is a slight negative progression among the data. As temperature increases, yield decreases.</p>
<p>The estimate from the simple linear model is negative, which supports the illustration in the graph. However, the p value from the simple linear regression is greater than alpha = 0.05, so we do not have sufficient evidence to conclude that there is a relationship.</p>
<p>When mean temp max squared was added as an estimate in the model, the significance of the temperature predictors changed to less than alpha = 0.05. We can conclude from this model with temp and temp^2 as predictors, that there is a relationship between temperature and yield.</p>
</div>
<div id="question-4-panel-one-way-to-leverage-multiple-time-series-is-to-group-all-data-into-what-is-called-a-panel-regression.-convert-the-county-id-code-countyfp-or-county_ansi-into-factor-using-as.factor-then-include-this-variable-in-a-regression-using-all-counties-yield-and-summer-temperature-data.-how-does-the-significance-of-your-temperature-coefficients-tmax-tmax2-change-make-a-plot-comparing-actual-and-fitted-yields-and-interpret-the-results-of-your-model." class="section level3" number="17.6.5">
<h3><span class="header-section-number">17.6.5</span> Question 4 – Panel: One way to leverage multiple time series is to group all data into what is called a “panel” regression. Convert the county ID code (“countyfp” or “county_ansi”) into factor using as.factor, then include this variable in a regression using all counties’ yield and summer temperature data. How does the significance of your temperature coefficients (Tmax, Tmax^2) change? Make a plot comparing actual and fitted yields and interpret the results of your model.</h3>
<p>Convert county ID into factor and join temperature and yield data:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="blocks.html#cb121-1" aria-hidden="true" tabindex="-1"></a>yieldall <span class="ot">&lt;-</span> cornyieldsall <span class="sc">%&gt;%</span> </span>
<span id="cb121-2"><a href="blocks.html#cb121-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county_name) <span class="sc">%&gt;%</span> </span>
<span id="cb121-3"><a href="blocks.html#cb121-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb121-4"><a href="blocks.html#cb121-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_ansi))</span>
<span id="cb121-5"><a href="blocks.html#cb121-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-6"><a href="blocks.html#cb121-6" aria-hidden="true" tabindex="-1"></a>tempall <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb121-7"><a href="blocks.html#cb121-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(countyfp) <span class="sc">%&gt;%</span></span>
<span id="cb121-8"><a href="blocks.html#cb121-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(doy <span class="sc">&gt;=</span> <span class="dv">152</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;=</span> <span class="dv">243</span>) <span class="sc">%&gt;%</span></span>
<span id="cb121-9"><a href="blocks.html#cb121-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax)) <span class="sc">%&gt;%</span> </span>
<span id="cb121-10"><a href="blocks.html#cb121-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">county_ansi =</span> <span class="st">&quot;countyfp&quot;</span>)</span>
<span id="cb121-11"><a href="blocks.html#cb121-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-12"><a href="blocks.html#cb121-12" aria-hidden="true" tabindex="-1"></a>tempall<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(tempall<span class="sc">$</span>county_ansi))</span>
<span id="cb121-13"><a href="blocks.html#cb121-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-14"><a href="blocks.html#cb121-14" aria-hidden="true" tabindex="-1"></a>summeryieldall <span class="ot">&lt;-</span> <span class="fu">left_join</span>(yieldall, tempall, <span class="at">by=</span><span class="st">&#39;county_ansi&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb121-15"><a href="blocks.html#cb121-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., county_ansi, county_name, yield, meantmax, year)</span>
<span id="cb121-16"><a href="blocks.html#cb121-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-17"><a href="blocks.html#cb121-17" aria-hidden="true" tabindex="-1"></a>summeryieldall<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(summeryieldall<span class="sc">$</span>county_ansi)</span></code></pre></div>
<p>Run simple and multiple regression models:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="blocks.html#cb122-1" aria-hidden="true" tabindex="-1"></a>summeryieldall<span class="sc">$</span>meantmaxsq <span class="ot">&lt;-</span> summeryieldall<span class="sc">$</span>meantmax<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb122-2"><a href="blocks.html#cb122-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-3"><a href="blocks.html#cb122-3" aria-hidden="true" tabindex="-1"></a>lm_summeryieldall <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax <span class="sc">+</span> meantmaxsq, summeryieldall)</span>
<span id="cb122-4"><a href="blocks.html#cb122-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summeryieldall)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax + meantmaxsq, data = summeryieldall)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -121.002  -22.522   -0.525   26.442   86.550 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3680.191    844.714  -4.357 1.35e-05 ***
## meantmax      285.830     60.642   4.713 2.52e-06 ***
## meantmaxsq     -5.325      1.088  -4.894 1.02e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 35.29 on 4012 degrees of freedom
## Multiple R-squared:  0.0491, Adjusted R-squared:  0.04862 
## F-statistic: 103.6 on 2 and 4012 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="blocks.html#cb124-1" aria-hidden="true" tabindex="-1"></a>lm_summeryield_panel <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax <span class="sc">+</span> meantmaxsq <span class="sc">+</span> county_ansi, summeryieldall)</span>
<span id="cb124-2"><a href="blocks.html#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_summeryield_panel)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax + meantmaxsq + county_ansi, data = summeryieldall)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -115.150  -22.076   -0.895   25.952   82.566 
## 
## Coefficients: (2 not defined because of singularities)
##                  Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)    -8.131e+03  5.398e+03  -1.506  0.13206   
## meantmax        6.110e+02  3.926e+02   1.556  0.11971   
## meantmaxsq     -1.126e+01  7.133e+00  -1.578  0.11454   
## county_ansi3   -5.811e+00  7.676e+00  -0.757  0.44905   
## county_ansi5   -6.793e+00  6.844e+00  -0.992  0.32105   
## county_ansi7   -1.623e+01  8.253e+00  -1.967  0.04930 * 
## county_ansi9   -8.711e-01  7.185e+00  -0.121  0.90351   
## county_ansi11  -3.433e+00  7.612e+00  -0.451  0.65202   
## county_ansi13  -4.205e+00  7.649e+00  -0.550  0.58257   
## county_ansi15   7.454e+00  7.158e+00   1.041  0.29774   
## county_ansi17   1.167e-01  7.456e+00   0.016  0.98751   
## county_ansi19  -2.918e+00  7.323e+00  -0.398  0.69028   
## county_ansi21  -2.440e+00  7.683e+00  -0.318  0.75084   
## county_ansi23  -1.161e+00  7.690e+00  -0.151  0.87995   
## county_ansi25  -1.806e-02  7.650e+00  -0.002  0.99812   
## county_ansi27   2.105e+00  7.317e+00   0.288  0.77361   
## county_ansi29   7.371e+00  7.484e+00   0.985  0.32477   
## county_ansi31   5.293e+00  7.495e+00   0.706  0.48010   
## county_ansi33  -6.324e+00  7.010e+00  -0.902  0.36703   
## county_ansi35   3.255e+00  7.632e+00   0.427  0.66975   
## county_ansi37  -7.138e+00  6.879e+00  -1.038  0.29944   
## county_ansi39  -2.494e+01  8.065e+00  -3.092  0.00200 **
## county_ansi41  -5.117e+00  7.647e+00  -0.669  0.50343   
## county_ansi43  -2.358e+00  7.095e+00  -0.332  0.73960   
## county_ansi45   4.344e-01  7.583e+00   0.057  0.95432   
## county_ansi47  -4.662e-01  7.433e+00  -0.063  0.94999   
## county_ansi49   8.485e+00  7.137e+00   1.189  0.23453   
## county_ansi51  -3.678e+00  1.234e+01  -0.298  0.76561   
## county_ansi53  -1.479e+01  8.834e+00  -1.674  0.09413 . 
## county_ansi55  -1.107e+00  7.030e+00  -0.158  0.87485   
## county_ansi57   1.363e+01  8.795e+00   1.549  0.12139   
## county_ansi59  -9.503e+00  7.165e+00  -1.326  0.18479   
## county_ansi61  -3.571e-01  6.970e+00  -0.051  0.95914   
## county_ansi63  -4.546e+00  6.945e+00  -0.655  0.51274   
## county_ansi65  -2.783e+00  6.867e+00  -0.405  0.68530   
## county_ansi67  -6.171e+00  7.338e+00  -0.841  0.40041   
## county_ansi69  -3.550e-01  7.598e+00  -0.047  0.96274   
## county_ansi71   4.210e+01  2.262e+01   1.862  0.06275 . 
## county_ansi73   1.060e+01  6.991e+00   1.516  0.12966   
## county_ansi75   7.736e-01  7.678e+00   0.101  0.91974   
## county_ansi77   1.762e+00  7.078e+00   0.249  0.80347   
## county_ansi79   2.387e+00  7.541e+00   0.317  0.75156   
## county_ansi81  -1.474e+00  6.932e+00  -0.213  0.83160   
## county_ansi83   2.638e+00  7.629e+00   0.346  0.72948   
## county_ansi85   9.046e+00  8.676e+00   1.043  0.29715   
## county_ansi87   1.063e+01  9.601e+00   1.107  0.26822   
## county_ansi89  -2.675e+00  9.051e+00  -0.296  0.76757   
## county_ansi91  -1.429e+00  7.322e+00  -0.195  0.84531   
## county_ansi93   1.744e+00  7.641e+00   0.228  0.81945   
## county_ansi95  -2.068e-02  7.073e+00  -0.003  0.99767   
## county_ansi97  -1.294e+01  7.622e+00  -1.697  0.08976 . 
## county_ansi99   9.297e+00  7.064e+00   1.316  0.18818   
## county_ansi101  1.561e+01  1.485e+01   1.051  0.29331   
## county_ansi103 -2.953e+00  7.084e+00  -0.417  0.67680   
## county_ansi105 -5.033e+00  7.734e+00  -0.651  0.51521   
## county_ansi107  2.862e+00  7.820e+00   0.366  0.71439   
## county_ansi109  6.575e-01  7.222e+00   0.091  0.92746   
## county_ansi111  1.749e+01  1.488e+01   1.175  0.23988   
## county_ansi113 -5.180e+00  7.716e+00  -0.671  0.50201   
## county_ansi115  1.442e+01  1.007e+01   1.432  0.15209   
## county_ansi117 -2.228e+01  8.094e+00  -2.753  0.00593 **
## county_ansi119  2.612e-01  7.526e+00   0.035  0.97231   
## county_ansi121 -3.731e+00  7.171e+00  -0.520  0.60294   
## county_ansi123  8.888e+00  7.583e+00   1.172  0.24125   
## county_ansi125  1.991e+00  7.735e+00   0.257  0.79689   
## county_ansi127  3.870e+00  7.700e+00   0.503  0.61528   
## county_ansi129  2.855e+01  1.652e+01   1.728  0.08406 . 
## county_ansi131 -5.815e-02  7.260e+00  -0.008  0.99361   
## county_ansi133  8.667e+00  9.621e+00   0.901  0.36776   
## county_ansi135 -1.747e+01  7.455e+00  -2.344  0.01915 * 
## county_ansi137  1.680e+01  1.111e+01   1.512  0.13071   
## county_ansi139  7.588e+00  7.370e+00   1.030  0.30325   
## county_ansi141  3.578e+00  7.680e+00   0.466  0.64133   
## county_ansi143 -2.783e+00  7.080e+00  -0.393  0.69430   
## county_ansi145  1.119e+01  1.140e+01   0.982  0.32629   
## county_ansi147 -4.178e+00  7.624e+00  -0.548  0.58377   
## county_ansi149  1.951e+00  7.078e+00   0.276  0.78284   
## county_ansi151  4.138e-01  7.721e+00   0.054  0.95726   
## county_ansi153  1.348e+01  7.406e+00   1.820  0.06886 . 
## county_ansi155  1.546e+01  8.682e+00   1.780  0.07508 . 
## county_ansi157  5.593e+00  6.988e+00   0.800  0.42352   
## county_ansi159 -1.981e+01  7.825e+00  -2.532  0.01137 * 
## county_ansi161 -5.455e-01  7.676e+00  -0.071  0.94335   
## county_ansi163  7.564e+00  7.326e+00   1.032  0.30190   
## county_ansi165  3.609e-01  7.242e+00   0.050  0.96026   
## county_ansi167  8.327e+00  7.282e+00   1.144  0.25287   
## county_ansi169  1.817e-01  7.603e+00   0.024  0.98094   
## county_ansi171 -9.328e-01  7.608e+00  -0.123  0.90243   
## county_ansi173 -9.599e+00  8.955e+00  -1.072  0.28380   
## county_ansi175 -1.234e+01  7.352e+00  -1.678  0.09336 . 
## county_ansi177  2.064e+01  2.129e+01   0.969  0.33236   
## county_ansi179  3.311e+00  1.016e+01   0.326  0.74458   
## county_ansi181 -3.579e+00  7.771e+00  -0.461  0.64509   
## county_ansi183  1.459e+01  9.259e+00   1.576  0.11510   
## county_ansi185 -2.220e+01  7.476e+00  -2.970  0.00300 **
## county_ansi187  3.868e+00  7.664e+00   0.505  0.61381   
## county_ansi189 -1.066e+00  6.842e+00  -0.156  0.87621   
## county_ansi191 -3.217e+00  7.150e+00  -0.450  0.65273   
## county_ansi193  1.477e+00  7.009e+00   0.211  0.83310   
## county_ansi195         NA         NA      NA       NA   
## county_ansi197         NA         NA      NA       NA   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 34.65 on 3916 degrees of freedom
## Multiple R-squared:  0.1048, Adjusted R-squared:  0.08245 
## F-statistic:  4.68 on 98 and 3916 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="blocks.html#cb126-1" aria-hidden="true" tabindex="-1"></a>summeryieldall<span class="sc">$</span>fitted <span class="ot">&lt;-</span> lm_summeryield_panel<span class="sc">$</span>fitted.values</span></code></pre></div>
<p>Plot actual and fitted yields:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="blocks.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summeryieldall) <span class="sc">+</span></span>
<span id="cb127-2"><a href="blocks.html#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> yield, <span class="at">y =</span> fitted)) <span class="sc">+</span></span>
<span id="cb127-3"><a href="blocks.html#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> yield, <span class="at">y =</span> fitted),<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb127-4"><a href="blocks.html#cb127-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_few</span>() <span class="sc">+</span></span>
<span id="cb127-5"><a href="blocks.html#cb127-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Actual Yield&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Fitted Yield&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Fitted Versus Actual Corn Yields For Summer&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>Our panel regression model has an adjusted R-squared value of 0.08245, so only 8.245% of the variation within yield is explained by predictors. The mean max temperature and mean max temperature squared have p values greater than alpha = 0.05, so we do not have sufficient evidence to conclude that there is a relationship between these temperature values and corresponding yield.</p>
<p>The significance of the temperature coefficients changed when we added the county ansi to the model. When the linear model included mean max temperature and mean max temperature squared, the p values were less than alpha = 0.05, indicating statistical significance. When county ansi was added, the p values for the temperature coefficients increased to greater than alpha = 0.05, indicating a lack of statistical significance.</p>
</div>
<div id="question-5-soybeans-download-nass-data-on-soybean-yields-and-explore-either-a-time-series-relationship-for-a-given-county-the-cross-sectional-relationship-for-a-given-year-or-a-panel-across-all-counties-and-years." class="section level3" number="17.6.6">
<h3><span class="header-section-number">17.6.6</span> Question 5 – Soybeans: Download NASS data on soybean yields and explore either a time series relationship for a given county, the <strong>cross-sectional relationship for a given year</strong>, or a panel across all counties and years.</h3>
<p>Download soybean data:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="blocks.html#cb128-1" aria-hidden="true" tabindex="-1"></a>soybeanparams <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">commodity_desc =</span> <span class="st">&quot;SOYBEANS&quot;</span>, <span class="at">statisticcat_desc=</span> <span class="st">&quot;YIELD&quot;</span>, <span class="at">prodn_practice_desc =</span> <span class="st">&quot;ALL PRODUCTION PRACTICES&quot;</span>, <span class="at">year__GE =</span> <span class="dv">1981</span>, <span class="at">state_alpha =</span> <span class="st">&quot;IA&quot;</span>)</span>
<span id="cb128-2"><a href="blocks.html#cb128-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-3"><a href="blocks.html#cb128-3" aria-hidden="true" tabindex="-1"></a>soyall <span class="ot">&lt;-</span> <span class="fu">nassqs_yields</span>(soybeanparams)</span>
<span id="cb128-4"><a href="blocks.html#cb128-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-5"><a href="blocks.html#cb128-5" aria-hidden="true" tabindex="-1"></a>soyall<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(soyall<span class="sc">$</span>county_ansi)</span>
<span id="cb128-6"><a href="blocks.html#cb128-6" aria-hidden="true" tabindex="-1"></a>soyall<span class="sc">$</span>yield <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(soyall<span class="sc">$</span>Value)</span>
<span id="cb128-7"><a href="blocks.html#cb128-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-8"><a href="blocks.html#cb128-8" aria-hidden="true" tabindex="-1"></a>soyyield <span class="ot">&lt;-</span> <span class="fu">select</span>(soyall, county_ansi, county_name, yield, year) <span class="sc">%&gt;%</span></span>
<span id="cb128-9"><a href="blocks.html#cb128-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_ansi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(yield))</span>
<span id="cb128-10"><a href="blocks.html#cb128-10" aria-hidden="true" tabindex="-1"></a>soyyield <span class="ot">&lt;-</span> <span class="fu">tibble</span>(soyyield)</span></code></pre></div>
<p>Cross-sectional relationship of soybean yield and mean summer max temperature for the year 2015:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="blocks.html#cb129-1" aria-hidden="true" tabindex="-1"></a>soyyield2015 <span class="ot">&lt;-</span> soyall <span class="sc">%&gt;%</span> </span>
<span id="cb129-2"><a href="blocks.html#cb129-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2015</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb129-3"><a href="blocks.html#cb129-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county_name) <span class="sc">%&gt;%</span> </span>
<span id="cb129-4"><a href="blocks.html#cb129-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb129-5"><a href="blocks.html#cb129-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_ansi))</span>
<span id="cb129-6"><a href="blocks.html#cb129-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-7"><a href="blocks.html#cb129-7" aria-hidden="true" tabindex="-1"></a>soytemp2015 <span class="ot">&lt;-</span> tmaxdf <span class="sc">%&gt;%</span></span>
<span id="cb129-8"><a href="blocks.html#cb129-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(countyfp) <span class="sc">%&gt;%</span></span>
<span id="cb129-9"><a href="blocks.html#cb129-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2015</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb129-10"><a href="blocks.html#cb129-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(doy <span class="sc">&gt;=</span> <span class="dv">152</span> <span class="sc">&amp;</span> doy <span class="sc">&lt;=</span> <span class="dv">243</span>) <span class="sc">%&gt;%</span></span>
<span id="cb129-11"><a href="blocks.html#cb129-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">meantmax =</span> <span class="fu">mean</span>(tmax)) <span class="sc">%&gt;%</span> </span>
<span id="cb129-12"><a href="blocks.html#cb129-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">county_ansi =</span> <span class="st">&quot;countyfp&quot;</span>)</span>
<span id="cb129-13"><a href="blocks.html#cb129-13" aria-hidden="true" tabindex="-1"></a>soytemp2015<span class="sc">$</span>county_ansi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(soytemp2015<span class="sc">$</span>county_ansi))</span>
<span id="cb129-14"><a href="blocks.html#cb129-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-15"><a href="blocks.html#cb129-15" aria-hidden="true" tabindex="-1"></a>soy2015 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(soyyield2015, soytemp2015, <span class="at">by=</span><span class="st">&#39;county_ansi&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb129-16"><a href="blocks.html#cb129-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., county_ansi, county_name, yield, meantmax)</span>
<span id="cb129-17"><a href="blocks.html#cb129-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-18"><a href="blocks.html#cb129-18" aria-hidden="true" tabindex="-1"></a>lm_soyyield <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax, soy2015)</span>
<span id="cb129-19"><a href="blocks.html#cb129-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_soyyield)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax, data = soy2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.0568  -2.4976   0.2312   1.9743   9.3812 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 166.5497    16.0416  10.382  &lt; 2e-16 ***
## meantmax     -4.1582     0.6013  -6.915 5.38e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.657 on 95 degrees of freedom
## Multiple R-squared:  0.3348, Adjusted R-squared:  0.3278 
## F-statistic: 47.82 on 1 and 95 DF,  p-value: 5.384e-10</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="blocks.html#cb131-1" aria-hidden="true" tabindex="-1"></a>soy2015<span class="sc">$</span>meantmaxsq <span class="ot">&lt;-</span> soy2015<span class="sc">$</span>meantmax<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb131-2"><a href="blocks.html#cb131-2" aria-hidden="true" tabindex="-1"></a>lm_soy2015_quad <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> meantmax <span class="sc">+</span> meantmaxsq, soy2015)</span>
<span id="cb131-3"><a href="blocks.html#cb131-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_soy2015_quad)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ meantmax + meantmaxsq, data = soy2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.8646  -2.3046   0.4521   1.5551   8.7845 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) -995.3104   603.6188  -1.649   0.1025  
## meantmax      82.7546    45.1420   1.833   0.0699 .
## meantmaxsq    -1.6245     0.8437  -1.925   0.0572 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.606 on 94 degrees of freedom
## Multiple R-squared:   0.36,  Adjusted R-squared:  0.3464 
## F-statistic: 26.44 on 2 and 94 DF,  p-value: 7.744e-10</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="blocks.html#cb133-1" aria-hidden="true" tabindex="-1"></a>soy2015<span class="sc">$</span>fitted <span class="ot">&lt;-</span> lm_soy2015_quad<span class="sc">$</span>fitted.values</span>
<span id="cb133-2"><a href="blocks.html#cb133-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-3"><a href="blocks.html#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(soy2015, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb133-4"><a href="blocks.html#cb133-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb133-5"><a href="blocks.html#cb133-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Soybean Yield and Mean Maximum Summer Temperature&quot;</span>) <span class="sc">+</span></span>
<span id="cb133-6"><a href="blocks.html#cb133-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb133-7"><a href="blocks.html#cb133-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="blocks.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(soy2015) <span class="sc">+</span></span>
<span id="cb134-2"><a href="blocks.html#cb134-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb134-3"><a href="blocks.html#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fitted)) <span class="sc">+</span></span>
<span id="cb134-4"><a href="blocks.html#cb134-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb134-5"><a href="blocks.html#cb134-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Soybean Yield and Quadratic Trend of Mean Maximum Summer Temperature&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-2.png" width="672" /></p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="blocks.html#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(soy2015) <span class="sc">+</span></span>
<span id="cb135-2"><a href="blocks.html#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> yield)) <span class="sc">+</span></span>
<span id="cb135-3"><a href="blocks.html#cb135-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> meantmax, <span class="at">y =</span> fitted), <span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb135-4"><a href="blocks.html#cb135-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb135-5"><a href="blocks.html#cb135-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean Max Temperature (°C)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Yield (bu/acre)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Soybean Yield and Quadratic Trend of Mean Maximum Summer Temperature&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-3.png" width="672" /></p>
<p>A simple linear regression of mean summer temperature and yield gives an R-squared value of 0.3348. We get a negative estimate of mean max summer temperature, indicating that as mean temperature decreases, yield increases. This finding is supported by the graph showing the relationship between yield and mean max temperature. This graph shows the data moving along a negative slope. The p value for the mean max temperature estimate is less than alpha = 0.05, suggesting we have enough evidence to claim a relationship between the predictor and yield.</p>
<p>However, when we add mean max summer temperature squared to the model, the p value changes for each predictor to be greater than alpha = 0.05, so we cannot claim to have sufficient evidence to reject the null hypothesis using this model.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="class-work.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sharing-your-book.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/05-blocks.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
